### ISSUE TITLE
Im a noob but I actually want to figure this out lol.

### ISSUE THREAD

**Issue by Cheesedoosh** [sternd/nitrado-ark-status-bot#27]
So Ive installed python and pip. I ran your installation code with the corrected file path for the package folder.  Once I run it, I get   File "ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

C:\Users\"username">PYTHONPATH="C:\Users\"username"\Downloads\nitrado-ark-status-bot-master:$PYTHONPATH"
'PYTHONPATH' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ADarkQueenRises** [comment]
Hey to join Bics discord and to get access to the V2 bot!!
Heres the link https://discord.gg/xPzF6HA

**Comment by Cheesedoosh** [comment]
?

**Comment by sternd** [comment]
Hey @harleyq44! This repository is very out of date. I have moved over to GitLab for all new development, and you can see the corresponding bot here: [Status Bot V2](https://gitlab.com/BIC_Dev/status-bot-v2/). In addition to this, if you'd like to learn more about the bots, you can chat with me on the [BIC Development Discord Server](https://discord.gg/rG6yAyqyJP).
