### ISSUE TITLE
Discord bot

### ISSUE THREAD

**Issue by harleyq44** [sternd/nitrado-ark-status-bot#29]
For Nitrado,

**Comment by sternd** [comment]
Hey @harleyq44! This repository is very out of date. I have moved over to GitLab for all new development, and you can see the corresponding bot here: [Status Bot V2](https://gitlab.com/BIC_Dev/status-bot-v2/). In addition to this, if you'd like to learn more about the bots, you can chat with me on the [BIC Development Discord Server](https://discord.gg/rG6yAyqyJP).
